### PR TITLE
Move more code

### PR DESCRIPTION
**Pull request by jdidion**
* Push more common code into wdlTools and update to the latest wdlTools (0.3.0)
* Clean up build.sbt
* Use proper semver, with the next release to be 2.0.0-rc2
* Get rid of Furl and use FileSource instead
* Implement DxFileAccessProtocol
* Add description cache to DxFile - this is handled by a base class, which eventually all data objects should extend
* Encapsulate DxFileDescription caching logic in DxFileDescCache, and use this in place of fileInfoDir
* Switch from List to Vector (which has better performance)
* Where possible, have commonly used objects (such as WdlVarLinksConverter) created in Main, rather than each class creating it's own instance (it doesn't keep any mutable state, so no reason to use separate instances)
* Use dynamically created temp directories rather than relying on the existance of /tmp

### CODE REVIEW

**Comment by jdidion** [comment]
Sorry, this is another big one - I promise this is the last one. Most of the changes are removing code in dxWDL that has been moved into wdlTools.

**Comment by jdidion** [comment]
CI is failing because we're still waiting on wdlTools 0.3.0 to show up in Maven Central

**Comment by jdidion** [comment]
Ok, I will split this into a couple of PRs

**Comment by commandlinegirl** [comment]
@jdidion Can this one be closed (without merging)?

**Pull request closed without merging**
