### PR TITLE
adding Dockerfile

### LINKED ISSUE #155: Docker container
Instead of needing to install on the host, it would be great to have a Docker container provided for the user. Would this be possible?

### PR DESCRIPTION
**Pull request by vsoch**
Hey @orodeh ! Here is a first shot at a Dockerfile (and corresponding instructions for building and using). I didn't provide a specific command for the user to test, but can add one per your suggestion if you think necessary.

Please see the files below for:

 - The Dockerfile
 - The Docker.md (instructions) for general use
 - [Docker Hub](https://hub.docker.com/r/vanessa/dx-toolkit/) for a demo container that I've pushed.

This PR will close #155.

### CODE REVIEW

**Comment by orodeh** [comment]
This is a nice addition. Can you please remove from the `doc/Docker.md` file the sections showing the command line usage of dxWDL.jar? There are two such places. If you think it is really necessary, you can link to the `doc/ExpertOptions.md` document. 

```
Actions:
  compile <WDL file>
    Compile a wdl file into a dnanexus workflow.
    Optionally, specify a destination path on the
```

If these instructions are linked from the top-level README.md, they become part of the official documentation, and need to pass the travis build for continuous integration. If you want to take that route, please take a look at the `.travis.yml` file. Travis is a way to make sure that a user picking up the docker image has reasonable confidence that it would work. 

An easier option is to open a `contrib` subdirectory, and place the `Docker.md` file there. You can create a matching `contrib` section in the top-level README and link from there. This way, people can find it, but they are also warned that the instructions may require tweaking.

**Comment by vsoch** [comment]
okay, please take a look! I've reorganized and updated the docs.

**Comment by orodeh** [comment]
This is looking good! Two last things, and I will approve this PR.
1) Please move `Dockerfile` to the `contrib` directory
2) If you want, you can open a `contrib` section in the top-level readme, and link to your code. This will make it easier for people to find. You can also add your name, it is your contribution :-)

**Comment by vsoch** [comment]
You got it! Actually I had done the first, and forgot to do the commit. Let me do these changes quickly now!

**Comment by vsoch** [comment]
How is that? I wasn't sure who / what the other contributions constitute, so I just added the one with an obvious association. Please edit/tweak to improve this if you know this information!

**Comment by orodeh** [comment]
@vsoch, thank you, it is merged!

**Comment by vsoch** [comment]
woohoo! And thank you! :)

**Pull request merged**
