### PR TITLE
Migrate to Scalafmt

### PR DESCRIPTION
**Pull request by sstadick**
The scalafmt branch has been formatted by [scalafmt](https://scalameta.org/scalafmt/) with default options + allowing for line width 100. A .scalafmt.conf file has been added to the project root. The major difference between this scalafmt'd code and previous is that [scala specifies](https://docs.scala-lang.org/style/indentation.html) 2 spaces for indentation where we were using 4. I can go back to 4 if we would like to. The Internals doc specifying code style has been updated to mandate scalafmt as well.

All tests pass with the exception of one that was already failing on master.

### CODE REVIEW

**Comment by orodeh** [comment]
I am not sure about this. 

Some of the lines here are *really* too short, for example:
https://github.com/dnanexus/dxWDL/pull/349/files#diff-5eceaaa2b315a54bf15aa54c2176dbb4L41

In this case the original is much more readable than the formatted one:
https://github.com/dnanexus/dxWDL/pull/349/files#diff-5eceaaa2b315a54bf15aa54c2176dbb4L150

Where did this code go?
https://github.com/dnanexus/dxWDL/pull/349/files#diff-984c6b1c8326934bf28ea7d7e51678fbL143

I prefer a four space indentation, because it makes the code more readable. I am open to other opinions though.

**Comment by sstadick** [comment]
Unfortunately it looks like scalafmt is adamant regarding 2 spaces for indents. https://github.com/scalameta/scalafmt/issues/1493

I think I can get scalafmt to look more like the original code with a little work, but are we willing to go with 2 instead of 4 spaces? It would be nice to have some standard formatted, but I'm not tied to this if you think it's not worth the effort right now.

**Comment by orodeh** [comment]
I am willing to go with the standard indentation of 2, if you can get the other lines to look better.

**Comment by sstadick** [comment]
How does this look in comparison? https://github.com/dnanexus/dxWDL/commit/1458df46c7583ff7b13b527476cfad357019e0a4#diff-5eceaaa2b315a54bf15aa54c2176dbb4L150 compare to your comment above: https://github.com/dnanexus/dxWDL/pull/349/files#diff-5eceaaa2b315a54bf15aa54c2176dbb4L150

It's scalafmt with options generated to be as close to the original code style as possible (except indent width).

**Comment by orodeh** [comment]
This is good enough for me. I am sure I'll find things to object to down the road, but we can go forward with this. It is preferable, in my opinion, to use the Scala standards when and if possible.

**Comment by sstadick** [comment]
Closing this PR and branch in favor of scalafmt-part2 branch which has the changes mentioned above: https://github.com/dnanexus/dxWDL/pull/352

**Pull request closed without merging**
